src/academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('user/', include('user.urls')),
    path('education/', include('education.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
]

src/user/models.py
from email.policy import default
import os
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from APA_module.apa_validations import is_valid_iran_code, validate_image


def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = '%s.%s' % (uuid.uuid4(), ext)
    return os.path.join(f'user/{instance.id}/profile_image/', filename)

def get_default_profile_image():
	return "logos/user.png"


class User(AbstractUser):
    email               = models.EmailField(verbose_name='ایمیل', unique=True)
    national_code       = models.CharField(verbose_name='کد ملی',validators=[is_valid_iran_code], null=True, max_length=10)
    mobile_number1      = models.CharField(verbose_name='شماره همراه', max_length=11, null=True,blank = True, unique=True)
    mobile_number2      = models.CharField(verbose_name='شماره همراه', max_length=11, null=True,blank = True, unique=True)
    birthdate           = models.IntegerField(verbose_name='سال تولد', blank=True, null=True)
    address             = models.CharField(verbose_name='آدرس', max_length=200, blank=True, default='اهواز')
    profile_picture     = models.ImageField(verbose_name='عکس پروفایل', validators=[validate_image], upload_to=get_file_path, default=get_default_profile_image, null=True, blank=True)

    def __str__(self):
        return str(self.id)

src/user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from user.models import User


class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = "__all__" 


class UpdateProfileForm(forms.ModelForm):

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email', 'national_code', 'mobile_number1', 'mobile_number2', 'birthdate', 'address', 'profile_picture']

src/user/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import (get_object_or_404, HttpResponseRedirect)
from django.urls import reverse
from user.models import User
from user.forms import UpdateProfileForm


def home(request):
    user_obj = get_object_or_404(User, id=request.user.id)
    user_form = UpdateProfileForm(request.POST or None, request.FILES or None, instance=user_obj)
    context = {
        'user':user_form
    }
    return render (request, '_layout.html', context)

def profile(request, *args, **kwargs):
    user_obj = get_object_or_404(User, id=request.user.id)
    user_form = UpdateProfileForm(request.POST or None, request.FILES or None, instance=user_obj)
    context = dict()
    context.update({ 'user':user_form })

    if request.method == "POST":
        if user_form.is_valid():    
                user_form.save()
                context.update({ 'successfullsave':1 })
    
    return render(request, 'user/profile.html', context)


# def successfullsave(request):
#     return render(request,'successfullsave.html',{})

src/user/templates/user/profile.html
{% extends '_layout.html' %}
{% load static %}

{% block jsBlock %}
    <!-- Datatables -->
    <script src="{% static 'assets/vendors/datatables.net/js/jquery.dataTables.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-bs/js/dataTables.bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-buttons-bs/js/buttons.bootstrap.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-buttons/js/buttons.print.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-fixedheader/js/dataTables.fixedHeader.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-keytable/js/dataTables.keyTable.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-responsive-bs/js/responsive.bootstrap.js' %}"></script>
    <script src="{% static 'assets/vendors/datatables.net-scroller/js/dataTables.scroller.min.js' %}"></script>
    <script src="{% static 'assets/vendors/jszip/dist/jszip.min.js' %}"></script>
    <script src="{% static 'assets/vendors/pdfmake/build/pdfmake.min.js' %}"></script>
    <script src="{% static 'assets/vendors/pdfmake/build/vfs_fonts.js' %}"></script>
    <script src="{% static 'assets/vendors/select2/dist/js/select2.min.js' %}"></script>
    <script>
        $('input').addClass('form-control');
    </script>


    <script>
        $("#id_birthday_age").addClass('hidden');
    </script>

    <script>
        function normalizeDate(dateInt) {
        return dateInt.substring(0, 4) + '/' + dateInt.substring(4, 6) + '/' + dateInt.substring(6, 8);
        ;}
        document.getElementById("fromDate1").value=normalizeDate(document.getElementById("id_birthday_age").value)
        
    </script>
    <script>
            var element = document.getElementById("profile_picture-clear_id");
            element.classList.remove("form-control");
    </script>

<script>
$('#id_last_name').keypress(function (e) {
        var regex = new RegExp(/^[\u0600-\u06FF\s]+$/);
        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
        if (regex.test(str)) {
            return true;
        }
        else {
            e.preventDefault();
            return false;
        }
    });
    $('#id_first_name').keypress(function (e) {
        var regex = new RegExp(/^[\u0600-\u06FF\s]+$/);
        var str = String.fromCharCode(!e.charCode ? e.which : e.charCode);
        if (regex.test(str)) {
            return true;
        }
        else {
            e.preventDefault();
            return false;
        }
    });
    $('#id_mobileNumber').on('input', function (event) { 
    this.value = this.value.replace(/[^0-9]/g, '');
    });
    </script>
{% if successfullsave %}
<script>
$('#myModal').modal('show');
</script>
{% endif %}

<script>
    $("#id_birthdate").hide();
</script>
{% endblock %}

{% block cssBlock %}
    <!-- Datatables -->

    <link href="{% static 'assets/vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'assets/vendors/datatables.net-bs/css/dataTables.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendors/datatables.net-buttons-bs/css/buttons.bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'assets/vendors/datatables.net-fixedheader-bs/css/fixedHeader.bootstrap.min.css' %}"
          rel="stylesheet">
    <link href="{% static 'assets/vendors/datatables.net-responsive-bs/css/responsive.bootstrap.min.css' %}"
          rel="stylesheet">
    <link href="{% static 'assets/vendors/datatables.net-scroller-bs/css/scroller.bootstrap.min.css' %}"
          rel="stylesheet">

          <style>
            .hide{
              display:none;
            }
            </style>
            <style>
                .tree,
                .tree ul {
                    margin: 0;
                    padding: 0;
                    list-style: none
                }
        
                .tree ul {
                    margin-left: 1em;
                    position: relative
                }
        
                .tree ul ul {
                    margin-left: .5em
                }
        
                .tree ul:before {
                    content: "";
                    display: block;
                    width: 0;
                    position: absolute;
                    top: 0;
                    bottom: 0;
                    left: 0;
                    border-left: 1px solid
                }
        
                .tree li {
                    margin: 0;
                    padding: 0 1em;
                    line-height: 2em;
                    color: #369;
                    font-weight: 700;
                    position: relative
                }
        
                .tree ul li:before {
                    content: "";
                    display: block;
                    width: 10px;
                    height: 0;
                    border-top: 1px solid;
                    margin-top: -1px;
                    position: absolute;
                    top: 1em;
                    left: 0
                }
        
                .tree ul li:last-child:before {
                    background: #fff;
                    height: auto;
                    top: 1em;
                    bottom: 0
                }
        
                .indicator {
                    margin-right: 5px;
                }
        
                .tree li a {
                    text-decoration: none;
                    color: #369;
                }
        
                .tree li button,
                .tree li button:active,
                .tree li button:focus {
                    text-decoration: none;
                    color: #369;
                    border: none;
                    background: transparent;
                    margin: 0px 0px 0px 0px;
                    padding: 0px 0px 0px 0px;
                    outline: 0;
                }
        
                .limit_text{
                    white-space: nowrap;
                    overflow: hidden;
                    width: 380px;
                    height: 30px;
                    text-overflow: ellipsis; 
                }
            </style>
        
{% endblock %}


{% block pageContent %}
<style>
    .modal-body{
                font-size: 17px;
            }
    input[type="file"] {
  display: block;
}
.imageThumb {
  max-height: 75px;
  border: 2px solid;
  padding: 1px;
  cursor: pointer;
}
.pip {
  display: inline-block;
  margin: 10px 10px 0 0;
}

.remove {
  display: block;
  background: #444;
  border: 1px solid black;
  color: white;
  text-align: center;
  cursor: pointer;
}
.remove:hover {
  background: white;
  color: black;
}
.btn-file {
    position: relative;
    overflow: hidden;
}
.modal-dialog{
    width: 1000px;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
.top_title {
    top: -8px;
}
</style>
<div class="">
    <div class="x_panel">
        <div class="x_title bg-primary">
            <h2 class="pull-right">فرم ثبت</h2>
            <ul class="nav navbar-left panel_toolbox">
                <li>
                    <a class="close-link"><i class="fa fa-close"></i></a>
                </li>
                <li>
                    <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        
            <div class="x_content">
                <ul class="nav nav-tabs">
                    <li class="active" ><a id="organPorposTab" data-toggle="tab" href="#organPorpos"> اطلاعات پایه</a></li>
                  </ul>
                  <form action="" method="post" enctype="multipart/form-data" style="background-color: white" novalidate>
                    {% csrf_token %}
                <div class="tab-content" >
                    <div class="clearfix" style="padding: 15px;"></div>
                  <div id="organPorpos" class="tab-pane fade in active">
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">نام :</label>
                        {{user.first_name}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">نام خانوادگی :</label>
                    {{user.last_name}}
                    </div>
            
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">نام کاربری :</label>
                        {{user.username}}
                    </div>

                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-5 col-sm-3 col-xs-12 pull-right">کد ملی :</label>
                        {{user.national_code}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-5 col-sm-3 col-xs-12 pull-right">شماره تلفن ۱ :</label>
                        {{user.mobile_number1}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-5 col-sm-3 col-xs-12 pull-right">شماره تلفن ۲ :</label>
                        {{user.mobile_number2}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">تغییر عکس پروفایل :</label>
                        {{user.profile_picture}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">ایمیل :</label>
                        {{user.email}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">تاریخ تولد :</label>
                        <input type="text" class="form-control" id="fromDate1"
                            data-mddatetimepicker="true" data-trigger="click"
                            data-targetselector="#fromDate1" data-groupid="group1" data-fromdate="true"
                            data-enabletimepicker="false" data-placement="right"
                            onchange="datepicker1Change()"
                            >
                        {{user.birthdate}}
                    </div>
                    <div class="col-md-6 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right"> آدرس :</label>
                        {{user.address}}
                    </div>
                    <div class="clearfix"></div>
                  </div>

                    <div class="col-md-3 col-sm-4 col-xs-4 form-group pull-right">
                        <button type="submit" class="btn btn-success">ذخیره</button>
                    </div>
                    

            </div>
            </form>
            {% for field in user %}
            {% if field.errors %}
                <div class="alert alert-danger">
                    {{ field.label_tag }} {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        </div>

<!-- Modal -->
  <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            تغییرات شما با موفقیت ثبت شد
        </div>
        <div class="modal-footer">
            <button type="button" class="btn btn-danger" data-dismiss="modal">بستن پنجره</button>
        </div>
      </div>
    </div>
  </div>

    </div>
</div>


{% endblock %}