src/academy/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from user import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='home'),
    path('user/', include('user.urls')),
    path('education/', include('education.urls')),

]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

src/education/urls.py
from django.urls import path
from education import views

app_name = 'education'
urlpatterns = [
    # English Institute Urls
    path('english_institute_register/', views.english_institute_register, name='english_institute_register'),
    path('english_institute_edit/<int:id>', views.english_institute_edit, name='english_institute_edit'),
    path('english_institute_forms_list/', views.english_institute_forms_list, name='english_institute_forms_list'),
    path('delete_english_institute_forms_list/<int:id>', views.delete_english_institute_forms_list, name='delete_english_institute_forms_list'),
    path('send_english_institute_forms_list/<int:id>', views.send_english_institute_forms_list, name='send_english_institute_forms_list'),

    # None Profit institute urls 
    path('nonprofit_form_register/', views.nonprofit_form_register, name='nonprofit_form_register'),
    path('nonprofit_form_edit/<int:id>', views.nonprofit_form_edit, name='nonprofit_form_edit'),
    path('send_nonprofit_institute_forms_list/<int:id>', views.send_nonprofit_institute_forms_list, name='send_nonprofit_institute_forms_list'),
    path('delete_nonprofit_institute_forms_list/<int:id>', views.delete_nonprofit_institute_forms_list, name='delete_nonprofit_institute_forms_list'),

    # Supervisor form list Urls
    path('supervisor_forms_list/', views.supervisor_forms_list, name='supervisor_forms_list'),

    # Supervisor English Institute Urls
    path('supervisor_rejected_english_institute_forms_list/<int:id>', views.supervisor_rejected_english_institute_forms_list, name='supervisor_rejected_english_institute_forms_list'),
    path('supervisor_accepted_english_institute_forms_list/<int:id>', views.supervisor_accepted_english_institute_forms_list, name='supervisor_accepted_english_institute_forms_list'),

    # Supervisor Profit Institute Urls
    path('supervisor_nonprofit_institute_rejected_forms_list/<int:id>', views.supervisor_nonprofit_institute_rejected_forms_list, name='supervisor_nonprofit_institute_rejected_forms_list'),
    path('supervisor_nonprofit_institute_accepted_forms_list/<int:id>', views.supervisor_nonprofit_institute_accepted_forms_list, name='supervisor_nonprofit_institute_accepted_forms_list'),
]

src/user/urls.py
from django.urls import path
from user import views

app_name = 'user'
urlpatterns = [
    path('profile/', views.profile, name='profile'),
]

src/education/models.py
from django.db import models
from user.models import User
from APA_module import apa_datetime
import datetime
from django.core.validators import MaxValueValidator, MinValueValidator

Active   = 1
Deactive = -1
StatusChoices = (
    (Active, "فعال"),
    (Deactive, "غیر فعال"),
)

Private_Person = 1
legal_Person   = 2
PermissionChoieces = (
    (Private_Person, "شخص حقیقی"),
    (legal_Person, "شخص حقوقی"),
)

Male    = 1
Female  = 2
SexChoieces = (
    (Male, "مرد"),
    (Female, "زن"),
)

Registered = 1
Posted     = 2
Rejected   = 3
Accepted   = 4
SendStatus = (
    (Registered, "ثبت شده"),
    (Posted, "ارسال شده"),
    (Rejected, "رد شده"),
    (Accepted, "تایید شده"),
)

Institute                         = 1
ForeignLanguageTrainingCenter     = 2
NonProfitScientificTrainingCenter = 3
TypeChoieces = (
    (Institute, "آموزشگاه"),
    (ForeignLanguageTrainingCenter, "مرکز آموزشی آزاد علمی"),
    (NonProfitScientificTrainingCenter, "مرکز آموزشی زبان خارجی"),
)

class City(models.Model):
    """
    شهر
    """
    class Meta:
        verbose_name        = 'شهر'
        verbose_name_plural = 'A- شهر'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)
    def __str__(self):
        return str(self.name)

class District(models.Model):
    """
    منطقه
    """
    class Meta:
        verbose_name        = 'منطقه'
        verbose_name_plural = 'B- منطقه'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)
    def __str__(self):
        return str(self.name)

class Area(models.Model):
    """
    ناحیه
    """
    class Meta:
        verbose_name        = 'ناحیه'
        verbose_name_plural = 'C- ناحیه'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class StudyPeriod(models.Model):
    """
    دوره تحصیلی
    """
    class Meta:
        verbose_name        = 'دوره تحصیلی'
        verbose_name_plural = 'D- دوره تحصیلی'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class InstitueActivityType(models.Model):
    """
    نوع فعالیت موسسه
    """
    class Meta:
        verbose_name        = 'نوع فعالیت موسسه'
        verbose_name_plural = 'E- نوع فعالیت موسسه'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class EnglishInstitute(models.Model):
    """
    مرکز آموزش زبان خارجه
    """
    class Meta:
        verbose_name        = 'مرکز آموزش زبان خارجه'
        verbose_name_plural = 'F- مرکز آموزش زبان خارجه'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class EnglishInstituteDefineTerm(models.Model):
    """
    تعریف سطح دوره زبان خارجه
    """
    class Meta:
        verbose_name        = 'تعریف سطح دوره زبان خارجه'
        verbose_name_plural = 'G- تعریف سطح دوره زبان خارجه'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class EnglishInstituteRegister(models.Model):
    """
    فرم ثبت زبان خارجه
    """
    class Meta:
        verbose_name        = 'فرم ثبت زبان خارجه'
        verbose_name_plural = 'H- فرم ثبت زبان خارجه'

    user                    = models.ForeignKey(User, on_delete=models.PROTECT)
    english_institute       = models.ForeignKey("EnglishInstitute", on_delete=models.PROTECT)
    city                    = models.ForeignKey("City", on_delete=models.PROTECT)
    district                = models.ForeignKey("District", on_delete=models.PROTECT)
    area                    = models.ForeignKey("Area", on_delete=models.PROTECT)
    status                  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)
    send_status             = models.IntegerField('وضعیت ارسال', default=1, choices=SendStatus)
    type                    = models.IntegerField('نوع', default=3, choices=TypeChoieces)
    permission_type         = models.IntegerField('نوع مجوز', default=1, choices=PermissionChoieces)
    sex                     = models.IntegerField('جنسیت', default=1, choices=SexChoieces)
    score                   = models.IntegerField('امتیاز کیفیت بخشی مرکز', blank = True)
    name_founder            = models.CharField('نام و نام خانوادگی موسس', max_length=255)
    name_manager            = models.CharField('نام و نام خانوادگی مدیر', max_length=255)
    bin_number              = models.CharField('شماره حساب مرکز', max_length=255)
    bank                    = models.CharField('نزد بانک', max_length=255)
    branch                  = models.CharField('شعبه', max_length=255)

    def __str__(self):
        return str(self.id)


class EnglishInstituteForm(models.Model):
    """
    فرم آموزش زبان خارجه
    """
    class Meta:
        verbose_name        = 'فرم آموزش زبان خارجه'
        verbose_name_plural = 'I- فرم آموزش زبان خارجه'

    english_institute_define_term       = models.ForeignKey("EnglishInstituteDefineTerm", on_delete=models.PROTECT)
    english_institute_register          = models.ForeignKey("EnglishInstituteRegister", on_delete=models.CASCADE)
    education_content                   = models.CharField('محتوا آموزشی', max_length=255)
    session_number                      = models.IntegerField('تعداد جلسات',)
    max_student                         = models.IntegerField('حداکثر تعداد دانش آموز',)
    session_price                       = models.IntegerField('نرخ یک جلسه آموزشی',)
    nsession_price                      = models.IntegerField('نرخ یک دوره آموزشی بر اساس N جلسه',)

    def __str__(self):
        return str(self.id)


class NonprofitInstitue(models.Model):
    """
    مرکز آموزشی علمی آزاد
    """
    class Meta:
        verbose_name        = 'مرکز آموزشی علمی آزاد'
        verbose_name_plural = 'J- مرکز آموزشی علمی آزاد'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class NonprofitInstituteDefineTerm(models.Model):
    """
    تعریف سطح دوره علمی آزاد
    """
    class Meta:
        verbose_name        = 'تعریف سطح دوره علمی آزاد'
        verbose_name_plural = 'K- تعریف سطح دوره علمی آزاد'

    name    = models.CharField('نام', max_length=255, unique=True, )
    status  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)

    def __str__(self):
        return str(self.name)


class NonprofitInstituteRegister(models.Model):
    """
    فرم ثبت مرکز علمی آزاد
    """
    class Meta:
        verbose_name        = 'فرم ثبت علمی آزاد'
        verbose_name_plural = 'L- فرم ثبت علمی آزاد'


    user                    = models.ForeignKey(User, on_delete=models.PROTECT)
    nonproft_institute      = models.ForeignKey("NonprofitInstitue", on_delete=models.PROTECT)
    city                    = models.ForeignKey("City", on_delete=models.PROTECT)
    district                = models.ForeignKey("District", on_delete=models.PROTECT)
    area                    = models.ForeignKey("Area", on_delete=models.PROTECT)
    status                  = models.IntegerField('وضعیت', default=1, choices=StatusChoices)
    send_status             = models.IntegerField('وضعیت ارسال', default=1, choices=SendStatus)
    type                    = models.IntegerField('نوع', default=2, choices=TypeChoieces)
    permission_type         = models.IntegerField('نوع مجوز', default=1, choices=PermissionChoieces)
    sex                     = models.IntegerField('جنسیت', default=1, choices=SexChoieces)
    score                   = models.IntegerField('امتیاز کیفیت بخشی مرکز', blank = True)
    name_founder            = models.CharField('نام و نام خانوادگی موسس', max_length=255)
    name_manager            = models.CharField('نام و نام خانوادگی مدیر', max_length=255)
    bin_number              = models.CharField('شماره حساب مرکز', max_length=255)
    bank                    = models.CharField('نزد بانک', max_length=255)
    branch                  = models.CharField('شعبه', max_length=255)

    def __str__(self):
        return str(self.id)



class NonprofitInstituteForm(models.Model):
    """
    فرم آموزش مرکز علمی آزاد
    """
    class Meta:
        verbose_name        = 'فرم آموزش علمی آزاد'
        verbose_name_plural = 'M- فرم آموزش علمی آزاد'

    nonprofit_institute_define_term         = models.ForeignKey("NonprofitInstituteDefineTerm", on_delete=models.PROTECT)
    nonprofit_institute_register            = models.ForeignKey("NonprofitInstituteRegister", on_delete=models.CASCADE)
    education_content                       = models.CharField('محتوا آموزشی', max_length=255)
    session_number                          = models.IntegerField('تعداد جلسات',)
    max_student                             = models.IntegerField('حداکثر تعداد دانش آموز',)
    max_hour                                = models.IntegerField('میزان کل ساعت دوره',)
    tuition                                 = models.IntegerField('شهریه مصوب دوره',)

    def __str__(self):
        return str(self.id)


class RejectedEnglishInstituteFormList(models.Model):
    """
    رد کردن فرم زبان خارجه
    """
    class Meta:
        verbose_name        = 'رد کردن فرم زبان خارجه'
        verbose_name_plural = 'N- رد کردن فرم زبان خارجه'

src/education/forms.py
from django import forms
from education import models

class EnglishInstituteRegisterForm(forms.ModelForm):
    class Meta:
        model = models.EnglishInstituteRegister
        fields = "__all__"
        exclude = ("status","send_status","type")


class NonprofitInstituteRegisterForm(forms.ModelForm):
    class Meta:
        model = models.NonprofitInstituteRegister
        fields = "__all__"
        exclude = ("status","send_status","type")

src/education/templates/education/english_institude_register.html
{% extends '_layout.html' %}
{% load static %}
{% block jsBlock %}
<script src="{% static 'assets/vendors/select2/dist/js/select2.min.js' %}"></script>

<script>
    </script>
     <script>
        $('input[type=file]').addClass('form-control');
        $('input[type=number]').addClass('form-control');
        $('input[type=text]').addClass('form-control');
        $('input[type=email]').addClass('form-control');
        $('select').addClass('form-control');
        $(document).ready(function () { $('select').select2();});
        // $("#id_name_founder").attr("placeholder", "نام و نام خانوادگی موسس");
        // $("#id_name_manager").attr("placeholder", "نام و نام خانوادگی مدیر");
        // $("#id_score").attr("placeholder", "امتیاز کیفیت بخشی");
        // $("#id_bin_number").attr("placeholder", "شماره حساب مرکز");
        // $("#id_bank").attr("placeholder", "نزد بانک");
        // $("#id_branch").attr("placeholder", "شعبه");
        // $("#id_english_institute").attr("placeholder", "آموزشگاه");


    </script>



    {% endblock %}

    {% block cssBlock %}
    <link href="{% static 'assets/vendors/select2/dist/css/select2.min.css' %}" rel="stylesheet" />
    <link href="{% static 'custom.css' %}" rel="stylesheet"/>
    <style>
        span.select2.select2-container.select2-container--default {
            width: 100% !important;
        }
        p{
            font-weight: bold;
        }
    </style>

    {% endblock %}

    {% block pageContent %}
    <div class="">
        <div class="tab-pane" role="tabpanel" id="complete">
            <div class="x_panel">
                <div class="x_title bg-primary">
                    <ul class="nav navbar-left panel_toolbox">
                        <li>
                            <a class="close-link"><i class="fa fa-close"></i></a>
                        </li>
                        <li>
                            <a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
                        </li>
                    </ul>
                    <div class="clearfix"></div>
                </div>

                <form action="" method="post" role="form" enctype="multipart/form-data" style="margin-top: -11px;">
                    {% csrf_token %}
                    <br>

                <div class="clearfix"></div>
                
                <input class="hidden" name="user" value="{{ request.user.id }}" type="number">

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> نام و نام خانوادگی موسس :</p>
                    {{ form.name_founder }}
                </div>
                
                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> نام و نام خانوادگی مدیر :</p>
                    {{ form.name_manager }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> امتیاز کیفیت بخشی :</p>
                    {{ form.score }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right">شماره حساب مرکز :</p>

                    {{ form.bin_number }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> نزد بانک :</p>

                    {{ form.bank }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right">  شعبه  :</p>

                    {{ form.branch }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> آموزشگاه :</p>
                    {{ form.english_institute }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> شهرستان :</p>
                    {{ form.city }}
                </div>
          

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> منطقه :</p>
                    {{ form.district }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> ناحیه :</p>
                    {{ form.area }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> نوع مجوز :</p>
                    {{ form.permission_type }}
                </div>

                <div class="col-md-4 col-sm-12 col-xs-12 form-group pull-right">
                    <p class="control-label col-md-4 col-sm-12 col-xs-12 pull-right"> جنسیت  :</p>
                    {{ form.sex }}
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12 form-group pull-right">

                    <div class="col-md-12 col-sm-12 col-xs-12 form-group pull-right">
                        <label class="control-label col-md-12 col-sm-12 col-xs-12 pull-right">
                            افزودن دوره  </label>

                    <div class="input-group" id="whoGroup" data-toggle="tooltip">

                        <select class="form-control" name ="english_term" id="english_term">
                            {% for term in terms %}
                            <option value="{{term.id}}"> {{term.name}}</option>
                        {% endfor %}
                        </select>     

                        <span class="input-group-btn">
                            <button type="button" onclick="AddInstitute()" class="btn btn-primary"><i
                                    class="fa fa-plus"></i></button>
                        </span>
                    </div>

                    <div class="col-md-12 col-sm-12 col-xs-12 form-group pull-right table-responsive">
                        <table  class="table table-striped table-bordered dt-responsive nowrap"
                            cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>سطح دوره</th>
                                    <th>محتوای اموزشی</th>
                                    <th>تعداد جلسات</th>
                                    <th> حداکثر تعداد دانش آموز در کلاس </th>
                                    <th>نرخ یک جلسه آموزشی 90 دقیقه</th>
                                    <th>نرخ یک دوره آموزشی بر اساس N جلسه</th>
                                    <th>حذف</th>
                                </tr>
                            </thead>
                            <tbody id="TblTerm">

                                {% for table_term in table_terms %}
                                <tr id="{{item.TeamMember.member}}">
                                    <td>
                                        {{ table_term.english_institute_define_term.name }}
                                        <input name='TermId' value='{{ table_term.english_institute_define_term.id }}' class='hidden'>
                                    </td>
                                    <td>
                                        <input name='education_content' required value="{{ table_term.education_content }}"   type='text'>
                                    </td>
                                    <td>
                                        <input name='session_number' required value="{{ table_term.session_number }}"   type='number'>
                                    </td>
                                    <td>
                                        <input name='max_student' required value="{{ table_term.max_student }}"   type='number'>
                                    </td>
                                    <td>
                                        <input name='session_price' required value="{{ table_term.session_price }}"   type='number'>
                                    </td>
                                    <td>
                                        <input name='nsession_price' required value="{{ table_term.nsession_price }}"   type='number'>
                                    </td>
                                    <td>
                                        <span class='glyphicon glyphicon-trash row-remover btn btn-danger '></span>
                                    </td>
                                </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>

                    <script>
                        let tableIndex = 0;
                        function AddInstitute() {

                            let val = $('#english_term').val();
                            let text = $("#english_term option:selected").text();
                            var x = document.getElementById("TblTerm").rows.namedItem(val);
                            console.log(x);
                            if (x == null) {
                                var table = document.getElementById("TblTerm");
                                var row = table.insertRow(tableIndex);
                                row.id = val;
                                var cell1 = row.insertCell(0);
                                var cell2 = row.insertCell(1);
                                var cell3 = row.insertCell(2);
                                var cell4 = row.insertCell(3);
                                var cell5 = row.insertCell(4);
                                var cell6 = row.insertCell(5);
                                var cell7 = row.insertCell(6);


                                cell1.innerHTML = text + "<input name='TermId' value='" + val + "' class='hidden'>";
                                cell2.innerHTML = "<input name='education_content' required   type='text'>"
                                cell3.innerHTML = "<input name='session_number' required min='1'  type='number'>"
                                cell4.innerHTML = "<input name='max_student' required min='1'  type='number'>"
                                cell5.innerHTML = "<input name='session_price' required min='1'  type='number'>"
                                cell6.innerHTML = "<input name='nsession_price' required min='1'  type='number'>"
                                cell7.innerHTML = "<span class='glyphicon glyphicon-trash row-remover btn btn-danger '></span>";
                                tableIndex++;
                            }
                        }
                        $("body").on('click', '.row-remover', function() {
                            $(this).closest('tr').remove();
                            tableIndex--;
                        });
                    </script>

                </div>


                  
                <div class="col-md-12 col-sm-12 col-xs-12 form-group pull-right">
                    <button type="submit" class="btn btn-primary">ذخیره</button>
                </div>
            </div>

        </div>
    </div>
    <div class="clearfix"></div>
    </div>
    </form>
    </div>
    </section>
    </div>
    </div>


    {% endblock pageContent %}